import { Match } from "./types";

export const TEAM_FLAGS: Record<string, string> = {
  "México": "🇲🇽",
  "Sudáfrica": "🇿🇦",
  "Corea del Sur": "🇰🇷",
  "República Checa": "🇨🇿",
  "Canadá": "🇨🇦",
  "Bosnia y Herzegovina": "🇧🇦",
  "Estados Unidos": "🇺🇸",
  "Paraguay": "🇵🇾",
  "Catar": "🇶🇦",
  "Suiza": "🇨🇭",
  "Brasil": "🇧🇷",
  "Marruecos": "🇲🇦",
  "Haití": "🇭🇹",
  "Escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Australia": "🇦🇺",
  "Turquía": "🇹🇷",
  "Alemania": "🇩🇪",
  "Curazao": "🇨🇼",
  "Países Bajos": "🇳🇱",
  "Japón": "🇯🇵",
  "Costa de Marfil": "🇨🇮",
  "Ecuador": "🇪🇨",
  "Suecia": "🇸🇪",
  "Túnez": "🇹🇳",
  "España": "🇪🇸",
  "Cabo Verde": "🇨🇻",
  "Bélgica": "🇧🇪",
  "Egipto": "🇪🇬",
  "Arabia Saudita": "🇸🇦",
  "Uruguay": "🇺🇾",
  "Irán": "🇮🇷",
  "Nueva Zelanda": "🇳🇿",
  "Francia": "🇫🇷",
  "Senegal": "🇸🇳",
  "Irak": "🇮🇶",
  "Noruega": "🇳🇴",
  "Argentina": "🇦🇷",
  "Argelia": "🇩🇿",
  "Austria": "🇦🇹",
  "Jordania": "🇯🇴",
  "Portugal": "🇵🇹",
  "RD Congo": "🇨🇩",
  "Inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Croacia": "🇭🇷",
  "Ghana": "🇬🇭",
  "Panamá": "🇵🇦",
  "Uzbekistán": "🇺🇿",
  "Colombia": "🇨🇴"
};

export const INITIAL_72_MATCHES: Match[] = [
  {
    id: "m_1",
    teamA: "México",
    teamB: "Sudáfrica",
    teamAFlag: "🇲🇽",
    teamBFlag: "🇿🇦",
    group: "Grupo A",
    stadium: "Estadio Ciudad de México",
    date: "2026-06-11T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_2",
    teamA: "Corea del Sur",
    teamB: "República Checa",
    teamAFlag: "🇰🇷",
    teamBFlag: "🇨🇿",
    group: "Grupo A",
    stadium: "Estadio Guadalajara",
    date: "2026-06-11T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_3",
    teamA: "Canadá",
    teamB: "Bosnia y Herzegovina",
    teamAFlag: "🇨🇦",
    teamBFlag: "🇧🇦",
    group: "Grupo B",
    stadium: "Estadio de Toronto",
    date: "2026-06-12T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_4",
    teamA: "Estados Unidos",
    teamB: "Paraguay",
    teamAFlag: "🇺🇸",
    teamBFlag: "🇵🇾",
    group: "Grupo D",
    stadium: "Estadio de Los Ángeles",
    date: "2026-06-12T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_5",
    teamA: "Catar",
    teamB: "Suiza",
    teamAFlag: "🇶🇦",
    teamBFlag: "🇨🇭",
    group: "Grupo B",
    stadium: "Estadio de la Bahía de San Francisco",
    date: "2026-06-13T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_6",
    teamA: "Brasil",
    teamB: "Marruecos",
    teamAFlag: "🇧🇷",
    teamBFlag: "🇲🇦",
    group: "Grupo C",
    stadium: "Estadio Nueva York / Nueva Jersey",
    date: "2026-06-13T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_7",
    teamA: "Haití",
    teamB: "Escocia",
    teamAFlag: "🇭🇹",
    teamBFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    group: "Grupo C",
    stadium: "Estadio de Boston",
    date: "2026-06-13T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_8",
    teamA: "Australia",
    teamB: "Turquía",
    teamAFlag: "🇦🇺",
    teamBFlag: "🇹🇷",
    group: "Grupo D",
    stadium: "Estadio BC Place (Vancouver)",
    date: "2026-06-14T01:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_9",
    teamA: "Alemania",
    teamB: "Curazao",
    teamAFlag: "🇩🇪",
    teamBFlag: "🇨🇼",
    group: "Grupo E",
    stadium: "Estadio de Houston",
    date: "2026-06-14T14:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_10",
    teamA: "Países Bajos",
    teamB: "Japón",
    teamAFlag: "🇳🇱",
    teamBFlag: "🇯🇵",
    group: "Grupo F",
    stadium: "Estadio de Dallas",
    date: "2026-06-14T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_11",
    teamA: "Costa de Marfil",
    teamB: "Ecuador",
    teamAFlag: "🇨🇮",
    teamBFlag: "🇪🇨",
    group: "Grupo E",
    stadium: "Estadio de Filadelfia",
    date: "2026-06-14T20:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_12",
    teamA: "Suecia",
    teamB: "Túnez",
    teamAFlag: "🇸🇪",
    teamBFlag: "🇹🇳",
    group: "Grupo F",
    stadium: "Estadio de Monterrey",
    date: "2026-06-14T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_13",
    teamA: "España",
    teamB: "Cabo Verde",
    teamAFlag: "🇪🇸",
    teamBFlag: "🇨🇻",
    group: "Grupo H",
    stadium: "Estadio de Atlanta",
    date: "2026-06-15T13:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_14",
    teamA: "Bélgica",
    teamB: "Egipto",
    teamAFlag: "🇧🇪",
    teamBFlag: "🇪🇬",
    group: "Grupo G",
    stadium: "Estadio de Seattle",
    date: "2026-06-15T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_15",
    teamA: "Arabia Saudita",
    teamB: "Uruguay",
    teamAFlag: "🇸🇦",
    teamBFlag: "🇺🇾",
    group: "Grupo H",
    stadium: "Estadio de Miami",
    date: "2026-06-15T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_16",
    teamA: "Irán",
    teamB: "Nueva Zelanda",
    teamAFlag: "🇮🇷",
    teamBFlag: "🇳🇿",
    group: "Grupo G",
    stadium: "Estadio de Los Ángeles",
    date: "2026-06-15T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_17",
    teamA: "Francia",
    teamB: "Senegal",
    teamAFlag: "🇫🇷",
    teamBFlag: "🇸🇳",
    group: "Grupo I",
    stadium: "Estadio Nueva York / Nueva Jersey",
    date: "2026-06-16T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_18",
    teamA: "Irak",
    teamB: "Noruega",
    teamAFlag: "🇮🇶",
    teamBFlag: "🇳🇴",
    group: "Grupo I",
    stadium: "Estadio de Boston",
    date: "2026-06-16T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_19",
    teamA: "Argentina",
    teamB: "Argelia",
    teamAFlag: "🇦🇷",
    teamBFlag: "🇩🇿",
    group: "Grupo J",
    stadium: "Estadio de Kansas City",
    date: "2026-06-16T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_20",
    teamA: "Austria",
    teamB: "Jordania",
    teamAFlag: "🇦🇹",
    teamBFlag: "🇯🇴",
    group: "Grupo J",
    stadium: "Estadio de la Bahía de San Francisco",
    date: "2026-06-17T01:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_21",
    teamA: "Portugal",
    teamB: "RD Congo",
    teamAFlag: "🇵🇹",
    teamBFlag: "🇨🇩",
    group: "Grupo K",
    stadium: "Estadio de Houston",
    date: "2026-06-17T14:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_22",
    teamA: "Inglaterra",
    teamB: "Croacia",
    teamAFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    teamBFlag: "🇭🇷",
    group: "Grupo L",
    stadium: "Estadio de Dallas",
    date: "2026-06-17T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_23",
    teamA: "Ghana",
    teamB: "Panamá",
    teamAFlag: "🇬🇭",
    teamBFlag: "🇵🇦",
    group: "Grupo L",
    stadium: "Estadio de Toronto",
    date: "2026-06-17T20:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_24",
    teamA: "Uzbekistán",
    teamB: "Colombia",
    teamAFlag: "🇺🇿",
    teamBFlag: "🇨🇴",
    group: "Grupo K",
    stadium: "Estadio Ciudad de México",
    date: "2026-06-17T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_25",
    teamA: "República Checa",
    teamB: "Sudáfrica",
    teamAFlag: "🇨🇿",
    teamBFlag: "🇿🇦",
    group: "Grupo A",
    stadium: "Estadio de Atlanta",
    date: "2026-06-18T13:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_26",
    teamA: "Suiza",
    teamB: "Bosnia y Herzegovina",
    teamAFlag: "🇨🇭",
    teamBFlag: "🇧🇦",
    group: "Grupo B",
    stadium: "Estadio de Los Ángeles",
    date: "2026-06-18T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_27",
    teamA: "Canadá",
    teamB: "Catar",
    teamAFlag: "🇨🇦",
    teamBFlag: "🇶🇦",
    group: "Grupo B",
    stadium: "Estadio BC Place (Vancouver)",
    date: "2026-06-18T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_28",
    teamA: "México",
    teamB: "Corea del Sur",
    teamAFlag: "🇲🇽",
    teamBFlag: "🇰🇷",
    group: "Grupo A",
    stadium: "Estadio Guadalajara",
    date: "2026-06-18T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_29",
    teamA: "Estados Unidos",
    teamB: "Australia",
    teamAFlag: "🇺🇸",
    teamBFlag: "🇦🇺",
    group: "Grupo D",
    stadium: "Estadio de Seattle",
    date: "2026-06-19T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_30",
    teamA: "Escocia",
    teamB: "Marruecos",
    teamAFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    teamBFlag: "🇲🇦",
    group: "Grupo C",
    stadium: "Estadio de Boston",
    date: "2026-06-19T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_31",
    teamA: "Brasil",
    teamB: "Haití",
    teamAFlag: "🇧🇷",
    teamBFlag: "🇭🇹",
    group: "Grupo C",
    stadium: "Estadio de Filadelfia",
    date: "2026-06-19T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_32",
    teamA: "Turquía",
    teamB: "Paraguay",
    teamAFlag: "🇹🇷",
    teamBFlag: "🇵🇾",
    group: "Grupo D",
    stadium: "Estadio de la Bahía de San Francisco",
    date: "2026-06-20T01:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_33",
    teamA: "Países Bajos",
    teamB: "Suecia",
    teamAFlag: "🇳🇱",
    teamBFlag: "🇸🇪",
    group: "Grupo F",
    stadium: "Estadio de Houston",
    date: "2026-06-20T14:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_34",
    teamA: "Alemania",
    teamB: "Costa de Marfil",
    teamAFlag: "🇩🇪",
    teamBFlag: "🇨🇮",
    group: "Grupo E",
    stadium: "Estadio de Toronto",
    date: "2026-06-20T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_35",
    teamA: "Curazao",
    teamB: "Ecuador",
    teamAFlag: "🇨🇼",
    teamBFlag: "🇪🇨",
    group: "Grupo E",
    stadium: "Estadio de Kansas City",
    date: "2026-06-20T21:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_36",
    teamA: "Túnez",
    teamB: "Japón",
    teamAFlag: "🇹🇳",
    teamBFlag: "🇯🇵",
    group: "Grupo F",
    stadium: "Estadio de Monterrey",
    date: "2026-06-21T01:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_37",
    teamA: "España",
    teamB: "Arabia Saudita",
    teamAFlag: "🇪🇸",
    teamBFlag: "🇸🇦",
    group: "Grupo H",
    stadium: "Estadio de Atlanta",
    date: "2026-06-21T13:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_38",
    teamA: "Bélgica",
    teamB: "Irán",
    teamAFlag: "🇧🇪",
    teamBFlag: "🇮🇷",
    group: "Grupo G",
    stadium: "Estadio de Los Ángeles",
    date: "2026-06-21T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_39",
    teamA: "Uruguay",
    teamB: "Cabo Verde",
    teamAFlag: "🇺🇾",
    teamBFlag: "🇨🇻",
    group: "Grupo H",
    stadium: "Estadio de Miami",
    date: "2026-06-21T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_40",
    teamA: "Nueva Zelanda",
    teamB: "Egipto",
    teamAFlag: "🇳🇿",
    teamBFlag: "🇪🇬",
    group: "Grupo G",
    stadium: "Estadio BC Place (Vancouver)",
    date: "2026-06-21T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_41",
    teamA: "Argentina",
    teamB: "Austria",
    teamAFlag: "🇦🇷",
    teamBFlag: "🇦🇹",
    group: "Grupo J",
    stadium: "Estadio de Dallas",
    date: "2026-06-22T14:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_42",
    teamA: "Francia",
    teamB: "Irak",
    teamAFlag: "🇫🇷",
    teamBFlag: "🇮🇶",
    group: "Grupo I",
    stadium: "Estadio de Filadelfia",
    date: "2026-06-22T18:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_43",
    teamA: "Noruega",
    teamB: "Senegal",
    teamAFlag: "🇳🇴",
    teamBFlag: "🇸🇳",
    group: "Grupo I",
    stadium: "Estadio Nueva York / Nueva Jersey",
    date: "2026-06-22T21:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_44",
    teamA: "Jordania",
    teamB: "Argelia",
    teamAFlag: "🇯🇴",
    teamBFlag: "🇩🇿",
    group: "Grupo J",
    stadium: "Estadio de la Bahía de San Francisco",
    date: "2026-06-23T00:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_45",
    teamA: "Portugal",
    teamB: "Uzbekistán",
    teamAFlag: "🇵🇹",
    teamBFlag: "🇺🇿",
    group: "Grupo K",
    stadium: "Estadio de Houston",
    date: "2026-06-23T14:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_46",
    teamA: "Inglaterra",
    teamB: "Ghana",
    teamAFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    teamBFlag: "🇬🇭",
    group: "Grupo L",
    stadium: "Estadio de Boston",
    date: "2026-06-23T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_47",
    teamA: "Panamá",
    teamB: "Croacia",
    teamAFlag: "🇵🇦",
    teamBFlag: "🇭🇷",
    group: "Grupo L",
    stadium: "Estadio de Toronto",
    date: "2026-06-23T20:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_48",
    teamA: "Colombia",
    teamB: "RD Congo",
    teamAFlag: "🇨🇴",
    teamBFlag: "🇨🇩",
    group: "Grupo K",
    stadium: "Estadio Guadalajara",
    date: "2026-06-23T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_49",
    teamA: "Suiza",
    teamB: "Canadá",
    teamAFlag: "🇨🇭",
    teamBFlag: "🇨🇦",
    group: "Grupo B",
    stadium: "Estadio BC Place (Vancouver)",
    date: "2026-06-24T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_50",
    teamA: "Bosnia y Herzegovina",
    teamB: "Catar",
    teamAFlag: "🇧🇦",
    teamBFlag: "🇶🇦",
    group: "Grupo B",
    stadium: "Estadio de Seattle",
    date: "2026-06-24T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_51",
    teamA: "Escocia",
    teamB: "Brasil",
    teamAFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    teamBFlag: "🇧🇷",
    group: "Grupo C",
    stadium: "Estadio de Miami",
    date: "2026-06-24T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_52",
    teamA: "Marruecos",
    teamB: "Haití",
    teamAFlag: "🇲🇦",
    teamBFlag: "🇭🇹",
    group: "Grupo C",
    stadium: "Estadio de Atlanta",
    date: "2026-06-24T19:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_53",
    teamA: "República Checa",
    teamB: "México",
    teamAFlag: "🇨🇿",
    teamBFlag: "🇲🇽",
    group: "Grupo A",
    stadium: "Estadio Ciudad de México",
    date: "2026-06-24T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_54",
    teamA: "Sudáfrica",
    teamB: "Corea del Sur",
    teamAFlag: "🇿🇦",
    teamBFlag: "🇰🇷",
    group: "Grupo A",
    stadium: "Estadio de Monterrey",
    date: "2026-06-24T22:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_55",
    teamA: "Ecuador",
    teamB: "Alemania",
    teamAFlag: "🇪🇨",
    teamBFlag: "🇩🇪",
    group: "Grupo E",
    stadium: "Estadio Nueva York / Nueva Jersey",
    date: "2026-06-25T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_56",
    teamA: "Curazao",
    teamB: "Costa de Marfil",
    teamAFlag: "🇨🇼",
    teamBFlag: "🇨🇮",
    group: "Grupo E",
    stadium: "Estadio de Filadelfia",
    date: "2026-06-25T17:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_57",
    teamA: "Túnez",
    teamB: "Países Bajos",
    teamAFlag: "🇹🇳",
    teamBFlag: "🇳🇱",
    group: "Grupo F",
    stadium: "Estadio de Dallas",
    date: "2026-06-25T20:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_58",
    teamA: "Japón",
    teamB: "Suecia",
    teamAFlag: "🇯🇵",
    teamBFlag: "🇸🇪",
    group: "Grupo F",
    stadium: "Estadio de Kansas City",
    date: "2026-06-25T20:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_59",
    teamA: "Turquía",
    teamB: "Estados Unidos",
    teamAFlag: "🇹🇷",
    teamBFlag: "🇺🇸",
    group: "Grupo D",
    stadium: "Estadio de Los Ángeles",
    date: "2026-06-25T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_60",
    teamA: "Paraguay",
    teamB: "Australia",
    teamAFlag: "🇵🇾",
    teamBFlag: "🇦🇺",
    group: "Grupo D",
    stadium: "Estadio de la Bahía de San Francisco",
    date: "2026-06-25T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_61",
    teamA: "Noruega",
    teamB: "Francia",
    teamAFlag: "🇳🇴",
    teamBFlag: "🇫🇷",
    group: "Grupo I",
    stadium: "Estadio de Boston",
    date: "2026-06-26T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_62",
    teamA: "Senegal",
    teamB: "Irak",
    teamAFlag: "🇸🇳",
    teamBFlag: "🇮🇶",
    group: "Grupo I",
    stadium: "Estadio de Toronto",
    date: "2026-06-26T16:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_63",
    teamA: "Uruguay",
    teamB: "España",
    teamAFlag: "🇺🇾",
    teamBFlag: "🇪🇸",
    group: "Grupo H",
    stadium: "Estadio Guadalajara",
    date: "2026-06-26T21:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_64",
    teamA: "Cabo Verde",
    teamB: "Arabia Saudita",
    teamAFlag: "🇨🇻",
    teamBFlag: "🇸🇦",
    group: "Grupo H",
    stadium: "Estadio de Houston",
    date: "2026-06-26T21:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_65",
    teamA: "Nueva Zelanda",
    teamB: "Bélgica",
    teamAFlag: "🇳🇿",
    teamBFlag: "🇧🇪",
    group: "Grupo G",
    stadium: "Estadio BC Place (Vancouver)",
    date: "2026-06-27T00:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_66",
    teamA: "Egipto",
    teamB: "Irán",
    teamAFlag: "🇪🇬",
    teamBFlag: "🇮🇷",
    group: "Grupo G",
    stadium: "Estadio de Seattle",
    date: "2026-06-27T00:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_67",
    teamA: "Panamá",
    teamB: "Inglaterra",
    teamAFlag: "🇵🇦",
    teamBFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    group: "Grupo L",
    stadium: "Estadio Nueva York / Nueva Jersey",
    date: "2026-06-27T18:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_68",
    teamA: "Croacia",
    teamB: "Ghana",
    teamAFlag: "🇭🇷",
    teamBFlag: "🇬🇭",
    group: "Grupo L",
    stadium: "Estadio de Filadelfia",
    date: "2026-06-27T18:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_69",
    teamA: "Colombia",
    teamB: "Portugal",
    teamAFlag: "🇨🇴",
    teamBFlag: "🇵🇹",
    group: "Grupo K",
    stadium: "Estadio de Miami",
    date: "2026-06-27T20:30:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_70",
    teamA: "RD Congo",
    teamB: "Uzbekistán",
    teamAFlag: "🇨🇩",
    teamBFlag: "🇺🇿",
    group: "Grupo K",
    stadium: "Estadio de Atlanta",
    date: "2026-06-27T20:30:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_71",
    teamA: "Jordania",
    teamB: "Argentina",
    teamAFlag: "🇯🇴",
    teamBFlag: "🇦🇷",
    group: "Grupo J",
    stadium: "Estadio de Dallas",
    date: "2026-06-27T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  },
  {
    id: "m_72",
    teamA: "Argelia",
    teamB: "Austria",
    teamAFlag: "🇩🇿",
    teamBFlag: "🇦🇹",
    group: "Grupo J",
    stadium: "Estadio de Kansas City",
    date: "2026-06-27T23:00:00-03:00",
    resultA: null,
    resultB: null,
    status: "scheduled"
  }
];
